## Numpy

NumPy (Numerical Python) is a powerful Python library used for:

* Working with arrays (like lists but faster and more efficient).
* Performing mathematical operations on large datasets.


### Why NumPy?
- It's faster than Python lists.
- It's widely used in data science and machine learning.
- It makes working with data easier (especially arrays, matrices, and numerical computations).

In [1]:
pip install Numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

## Basics of NumPy
1. Creating Arrays in NumPy are like lists, but more powerful.

### 1D Array (Vector):

In [3]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)


[1 2 3 4 5]


In [4]:
list = [1,2,3,4,5,6]
arry = np.array(list) # output in int value
arry1 = np.array(list,dtype=float) # output in float value
arry2 = np.array(list,dtype='U32') # output in string value
print(arry)
print(arry1)
print(arry2)
print(type(arry))

[1 2 3 4 5 6]
[1. 2. 3. 4. 5. 6.]
['1' '2' '3' '4' '5' '6']
<class 'numpy.ndarray'>


### 2D Array (Matrix):

In [5]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)


[[1 2 3]
 [4 5 6]]


### 3D array in NumPy 
* is like a collection of 2D arrays stacked together. Think of it as a cube of numbers. It has three dimensions: depth, rows, and columns.

In [6]:
import numpy as np

# Create a 3D array
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]],  # First 2D array
                   [[7, 8, 9], [10, 11, 12]]])  # Second 2D array

print(arr_3d)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### Array Properties


In [7]:
print("Shape:", arr_2d.shape)  # Rows and columns
print("Size:", arr_2d.size)    # Total elements
print("Data type:", arr_2d.dtype)  # Type of data


Shape: (2, 3)
Size: 6
Data type: int32


### Array Operations
* Add, subtract, multiply, and divide arrays easily:

In [8]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Addition:", a + b)    
print("Subtraction:", a - b) 
print("Multiplication:", a * b) 
print("Division:", b / a)   


Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [4.  2.5 2. ]


### Mathematical Operations
How to find the sum, mean, or maximum?


In [9]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Sum of a:", np.sum(a))
print("Mean of a:", np.mean(a))
print("Max of a:", np.max(a))
print("Min of a:", np.min(a))

print("Sum of b:", np.sum(b))
print("Mean of b:", np.mean(b))
print("Max of b:", np.max(b))
print("Min of b:", np.min(b))



Sum of a: 6
Mean of a: 2.0
Max of a: 3
Min of a: 1
Sum of b: 15
Mean of b: 5.0
Max of b: 6
Min of b: 4


## Indexing and Slicing
Just like lists, you can access specific elements:

In [10]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[0]) 
print(arr[-1]) 
print(arr[1:4]) 


10
50
[20 30 40]


In [11]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

print(arr_2d[0, 1])  # Element at row 0, column 1: 2
print(arr_2d[:, 1])  # All rows, column 1: [2 5]


2
[2 5]


### Attribuites of Numpy array
- NumPy arrays have several attributes that provide information about their structure, type, and memory usage.

In [12]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Number of Dimensions:", arr.ndim)
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Data Type:", arr.dtype)
print("Item Size:", arr.itemsize)
print("Total Memory (Bytes):", arr.nbytes)
print("Transpose:\n", arr.T)

Number of Dimensions: 2
Shape: (2, 3)
Size: 6
Data Type: int32
Item Size: 4
Total Memory (Bytes): 24
Transpose:
 [[1 4]
 [2 5]
 [3 6]]


## Useful functions in numpy 
- NumPy provides a wide variety of functions for arrays that allow you to manipulate, analyze, and process data efficiently. These functions fall into categories like creation, mathematics, statistics, reshaping, and logical operations

### np.array(): Creates an array from a list or tuple.

In [13]:
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


### np.zeros(): Creates an array filled with zeros.

In [14]:
zeros = np.zeros((2, 3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


### np.ones(): Creates an array filled with ones.

In [15]:
ones = np.ones((3, 2))
print(ones)


[[1. 1.]
 [1. 1.]
 [1. 1.]]


### np.eye(): Creates an identity matrix.

In [16]:
identity = np.eye(3)
print(identity)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### np.arange(): Creates an array with evenly spaced values.

In [17]:
arr = np.arange(1, 10, 2) #start 1 ,stop 10,step 2
print(arr)


[1 3 5 7 9]


### np.linspace(): Creates an array with a specific number of evenly spaced values.

In [18]:
arr = np.linspace(1, 10, 5)
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


### np.random.random(): Creates an array with random values between 0 and 1.


In [19]:
rand = np.random.random((2, 2))
print(rand)

[[0.97663312 0.59667586]
 [0.72474252 0.38235089]]


## Mathematical Functions

### np.sum(): Sums all elements or along a specific axis.

In [20]:
arr = np.array([[1, 2], [3, 4]])
print(np.sum(arr))  # Output: 10
print(np.sum(arr, axis=0))  # Column-wise sum: [4 6]
print(np.sum(arr, axis=1))  # Row-wise sum: [3 7]


10
[4 6]
[3 7]


### np.mean(): Calculates the mean (average).

In [21]:
arr = np.array([[1, 2], [3, 4]])
print(np.mean(arr))  # Output: 2.5


2.5


### np.max() / np.min(): Finds the maximum or minimum value.

In [22]:
arr = np.array([[15, 21], [31, 40]])
print(np.max(arr)) 
print(np.min(arr))  


40
15


### np.sqrt(): Calculates the square root of each element.

In [23]:
arr = np.array([[1, 2], [3, 4]])
print(np.sqrt(arr))
# Output:
# [[1.         1.41421356]
#  [1.73205081 2.        ]]


[[1.         1.41421356]
 [1.73205081 2.        ]]


### np.dot(): Performs matrix multiplication.

In [24]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(np.dot(a, b))

[[19 22]
 [43 50]]


## Statistical Functions

### np.std(): Computes the standard deviation.

In [25]:
arr = np.array([[1, 2], [3, 4]])
print(np.std(arr)) 


1.118033988749895


### np.var(): Computes the variance.

In [26]:
print(np.var(arr)) 


1.25


### np.median(): Finds the median.

In [27]:
print(np.median(arr)) 

2.5


## Reshaping Functions

### np.reshape(): Changes the shape of an array.

In [28]:
arr = np.arange(6)
reshaped = arr.reshape(2, 3)
print(reshaped)

[[0 1 2]
 [3 4 5]]


### np.ravel(): Flattens a multi-dimensional array into 1D.

In [29]:
print(reshaped.ravel())

[0 1 2 3 4 5]


### np.transpose(): Transposes rows and columns.

In [30]:
print(np.transpose(reshaped))

[[0 3]
 [1 4]
 [2 5]]


## Logical Operations

### np.where(): Returns indices where a condition is true.

In [31]:
arr = np.array([10, 15, 20, 25])
print(np.where(arr > 15))

(array([2, 3], dtype=int64),)


### np.all() / np.any(): Checks if all or any elements meet a condition.

In [32]:
print(np.all(arr > 5)) 
print(np.any(arr > 20))  


True
True


## Copying and Joining Arrays


### np.concatenate(): Joins arrays along a specific axis.

In [33]:
a = np.array([1, 2])
b = np.array([3, 4])
print(np.concatenate((a, b)))

[1 2 3 4]


### np.split(): Splits an array into multiple parts.

In [34]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(np.split(arr, 3))

[array([1, 2]), array([3, 4]), array([5, 6])]
